title : Holiam.kr
name: Holiam's Lab
description: 'Welcome to Holiam Laboratory'

markdown: kramdown
highlighter: rouge
javascript_enabled: true

featured_posts_title: Unrelated
featured_posts:
  - url: '#'
    title: 'Featured post #1'
  - url: '#'
    title: 'Featured post #2'
  - url: '#'
    title: 'Featured post #3'

collections:
  win:
    title: Windows
    default_open: false
    output: true
  dev:
    title: Develops
    default_open: true
    output: true
    
  ml:
    title: Machine Learning
    default_open: true
    output: true

defaults:
  - scope:
      type: Windows
    values:
      title: Windows
      permalink: /post/:title
  - scope:
      type: Develops
    values:
      title: Develops
      permalink: /post/:title

plugins:
  - jekyll-sitemap
