title : Holiam.kr
name: Holiam's Lab
description: 'Welcome to Holiam Laboratory'

markdown: kramdown
highlighter: rouge
javascript_enabled: true

featured_posts_title: Unrelated
featured_posts:
  - url: '#'
    title: 'Featured post #1'
  - url: '#'
    title: 'Featured post #2'
  - url: '#'
    title: 'Featured post #3'

collections:

  posts:
    title: Essays
    default_open: true
    output: true

    
defaults:

      
  - scope:
        type: post
    values:
        title: Windows
        permalink: /wins/:title
        
        
  - scope:
      type: post
    values:
      title: Essays
      permalink: /post/:title
      
  - scope:
      type: post
    values:
      title: News
      permalink: /news/:title

plugins:
  - jekyll-sitemap
