title : Holiam.kr
name: Holiam's Log
description: 'Welcome to Holiam Log'

markdown: kramdown
highlighter: rouge
javascript_enabled: true


collections:
  devs:
   title: Develops
   default_open: true
   output: true
  wins:
   title: Windows
   default_open: true
   output: true
  mls:
    title: Machine Learning
    default_open: true
    output: true
  vul:
    title: Vulnerability
    default_open: true
    output: true

defaults:
  - scope:
      type: posts
    values:
      title: Windows
      permalink: /wins/:title
  - scope:
      type: posts
    values:
      title: Develops
      permalink: /devs/:title
  - scope:
      type: posts
    values:
      title: Machine Learning
      permalink: /mls/:title
  - scope:
      type: posts
    values:
      title: Vulnerability
      permalink: /vul/:title
      
plugins:
  - jekyll-sitemap
