title : Holiam.kr
name: Holiam's Lab
description: 'Welcome to Holiam Laboratory'

markdown: kramdown
highlighter: rouge
javascript_enabled: true


collections: #콜랙터는 큰 분류 생성
  devs:
    title: Develops
    default_open: false
    output: true
  mls:
    title: Machine Learning
    default_open: true
    output: true
  wins:
    title: Windows
    default_open: true
    output: true
    
defaults: #생성한 분류에 포함시킬 옵션
      
  - scope:
        type: posts
    values:
        title: Windows
        permalink: /wins/:title
        
        
  - scope:
      type: posts
    values:
      title: Develops
      permalink: /post/:title
      
  - scope:
      type: posts
    values:
      title: Machine Learning
      permalink: /mls/:title

plugins:
  - jekyll-sitemap
