title : Holiam.kr
name: Holiam's Lab
description: 'Welcome to Holiam Laboratory'

markdown: kramdown
highlighter: rouge
javascript_enabled: true


collections:
  devs:
   title: Develops
   default_open: true
   output: true
  wins:
   title: Windows
   default_open: true
   output: true
  mls:
    title: Machine Learning
    default_open: true
    output: true
  cve:
    title: CVE
    default_open: true
    output: true
  revs:
    title: Reviews
    default_open: true
    output: true

defaults:
  - scope:
  type: posts
    values:
      title: Windows
      permalink: /wins/:title
  - scope:
      type: posts
    values:
      title: Develops
      permalink: /devs/:title
  - scope:
      type: posts
    values:
      title: Machine Learning
      permalink: /mls/:title
    - scope:
        type: posts
    values:
        title: Reviews
        permalink: /revs/:title
   - scope:
      type: posts
    values:
      title: CVE
      permalink: /cve/:title

plugins:
  - jekyll-sitemap
